### PR TITLE
Custom attribute value should be of type object instead of string to …

### PR DESCRIPTION
**Pull request by jonleigh**
…allow decimal values etc

### CODE REVIEW

**Comment by markalanevans** [comment]
+1 We need this also. You can't send boolean or int values.

**Comment by markalanevans** [comment]
@jonleigh looks like your fix will allow me to set ints, decimals & boolean values correct?

**Comment by markalanevans** [comment]
If you merge this and update NuGet we can sync all of our past users tomorrow ;)

**Comment by jonleigh** [comment]
@markalanevans Yep, this change allows decimals to be sent to Intercom.  We've had to store the dll in source control while we wait for the merge and release.

**Comment by khalilovcmd** [comment]
Thank you @markalanevans for reporting this and for the PR. Apologies if it caused inconvenience (+ @markalanevans )

If you don't mind, I have merged a PR that takes care of this, also fix tests, and fix this behaviour in `UsersClient` too.

**Comment by khalilovcmd** [comment]
@markalanevans The `Nuget` package is updated. You can get the latest Nuget `1.0.7`.

**Comment by markalanevans** [comment]
@khalilovcmd @jonleigh Thank you both so much! Moving forward ;)

**Pull request closed without merging**
