### PR TITLE
Updated Conversation Reply Model

### PR DESCRIPTION
**Pull request by JoeRall**
**Why?**
Updated model that's returned when replying to a message.

See [Docs](https://developers.intercom.com/intercom-api-reference/reference#replying-to-a-conversation)

**How?**
Simply changed the return value to be a a Conversation vs a ConversationPart as the documentation expects.

### CODE REVIEW

**Comment by JoeRall** [comment]
@rdosanjh Is there anything else you'd like to see in the PR? Would love to try and get these bits in and release an updated version of the nuget package.

**Comment by ianintercom** [comment]
@JoeRall - This change looks good, a test or two on this would be great! Would be happy to merge then

**Comment by JoeRall** [comment]
@ianintercom - Thanks for the feedback. I just posted some tests. Note that I didn't see any examples of using MOQ in this repo so I took a stab at one possible way to test the clients. I think a safer set of tests would require a little refactoring so we can override some of the protected methods inside the `Client` base class. But I didn't want the scope of this change to get too big. I think that'd warrant it's own pull request.

Let me know what you think and I'll make any necessary modifications as necessary. I'd really love to get these changes out the door and on nuget.

**Comment by JoeRall** [comment]
@ianintercom No worries at all. That makes sense if there's a big refactoring that's about to go down. I'll keep an eye on #145 

Let me know if there's anything else I can help with.

**Pull request merged**
