### PR TITLE
Remove RestSharp Dependency

### PR DESCRIPTION
**Pull request by michael-watson**
Updated Client to utilize HttpRequestMessage and HttpResponseMessage
instead of IRestClient and IRestRequest. Unit test were also updated
and verified passing.

### CODE REVIEW

**Comment by michael-watson** [comment]
Hey Intercom friends! I was hoping someone could review and test out my PR. I removed the RestSharp dependency and updated everything to use ```async/await``` with ```HttpClient```,```HttpRequestMessage```, and ```HttpResponseMessage```. I updated all the Unit Tests to allow asynchronous testing. 

I also routed each specific Client through a single static instance of `HttpClient`. This will give thread safety and a bunch of other benefits to stabilize the SDK. There is a great [blog post](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) about this if you are interested in the details.

It would be even better if in the future all Intercom http traffic is routed through a single instance of ```HttpClient```. This could be done by utilizing a Singleton implementation on the HttpClient and routing all the traffic to that singleton. I didn't want to implement this yet until we verified everything is working properly.

**Comment by iamcarbon** [comment]
Bump -- this also provides a clear path for a netstandard 2.0 target.

**Comment by iamcarbon** [comment]
Any progress on this?

**Comment by kmossco** [comment]
Hey @michael-watson and @iamcarbon thank you so much for taking the time to help us with this. This is amazing work and the reason we haven't merged it yet is that we are discussing internally whether we should remove RestSharp as a dependency and implement .NET Standard in the SDK itself, or if we should keep RestSharp as they are also working towards fully implementing this.

More on this discussion here: #43. We should have an update on this very soon. 👍

**Comment by alexeyzimarev** [comment]
RestSharp fully supports .NET Standard 2.0 and will be kept actual.

**Comment by kmossco** [comment]
Thank you so much for your work here @michael-watson! 👍 We are currently working on issuing a new release of the bindings with .NET Standard 2.0 support and hope to have it done in a few weeks. Not yet sure if we will remove the `RestSharp` dependency right now, so for now I'll close this one.

**Comment by michael-watson** [comment]
I agree with the update! The would fix pretty much all of the other issues. I only did that effort to migrate to `HttpClient`to get around this issue. 

👍

**Pull request closed without merging**
